export const translations = {
  bn: {
    appName: "Riptide",
    searchPlaceholder: "এখানে খুঁজুন...",
    loginRegister: "লগইন / রেজিস্টার",
    logout: "লগআউট",
    bilingualToggle: "English",
    myOrders: "আমার অর্ডারসমূহ",
    adminDashboard: "অ্যাডমিন প্যানেল",
    trackOrder: "অর্ডার ট্র্যাক",
    support: "সহায়তা",
    home: "মূল পাতা",
    shop: "দোকান",
    cart: "কার্ট",
    profile: "প্রোফাইল",
    
    // Categories
    allCategories: "সকল ক্যাটাগরি",
    digitalProduct: "ডিজিটাল প্রোডাক্ট",
    uniqueProduct: "ইউনিক প্রোডাক্ট",
    hotSell: "হট সেলিং প্রোডাক্ট",
    unspecified: "সাধারণ",
    
    // Banner / Slogans
    bannerTitle: "সেরা মূল্যে সেরা পণ্য",
    bannerSubtitle: "ডিজিটাল গাইডস, ইউনিক ডিল ও হট সেলিং কালেকশন নিয়ে চমৎকার সোপিং অভিজ্ঞতা!",
    shopNow: "এখনই কিনুন",
    
    // Home sections
    latestArrivals: "নতুন কালেকশন",
    viewAll: "সবগুলো দেখুন",
    noProducts: "কোনো প্রোডাক্ট পাওয়া যায়নি। দয়া করে পরে আবার চেষ্টা করুন!",
    soldOut: "স্টক শেষ",
    lowStock: "সীমিত স্টক",
    soldCountPostfix: "পিস ইতিমধ্যে বিক্রি হয়েছে! 🔥",
    piecesLeft: "পিস বাকি আছে",
    originalPrice: "আসল মূল্য",
    discountPercent: "ছাড়",
    regularPrice: "মূল্য",
    addToCart: "কার্টে যোগ করুন",
    buyNow: "সরাসরি কিনুন",
    
    // Details Page
    description: "পণ্য বিবরণী",
    variants: "ভেরিয়েন্ট",
    selectVariant: "ভেরিয়েন্ট সিলেক্ট করুন",
    quantity: "পরিমাণ",
    reviews: "রিভিউসমূহ",
    writeReview: "রিভিউ লিখুন",
    noReviews: "এখনো কোনো রিভিউ নেই। প্রথম রিভিউটি আপনিই দিন!",
    submitReview: "রিভিউ জমা দিন",
    rating: "রেটিং",
    addComment: "মন্তব্য লিখুন...",
    reviewSuccess: "রিভিউ সফলভাবে সংযুক্ত হয়েছে!",
    
    // Cart Page
    shoppingCart: "শপিং কার্ট",
    emptyCart: "আপনার কার্ট খালি আছে। অনুগ্রহ করে প্রোডাক্ট নির্বাচন করুন!",
    checkout: "চেকআউট করুন",
    subtotal: "সাবটোটাল",
    total: "সর্বমোট",
    remove: "মুছে ফেলুন",
    
    // Checkout Page
    checkoutTitle: "অর্ডার কনফার্ম করুন",
    shippingDetails: "ডেলিভারি ঠিকানা",
    firstName: "নামের প্রথম অংশ",
    lastName: "নামের শেষ অংশ",
    phone: "মোবাইল নম্বর",
    address: "পূর্ণাঙ্গ ঠিকানা",
    city: "জেলা / শহর",
    division: "বিভাগ",
    deliveryNotes: "অর্ডার নোট (ঐচ্ছিক)",
    orderSummary: "অর্ডার সারসংক্ষেপ",
    totalItems: "মোট আইটেম",
    shippingCharge: "ডেলিভারি চার্জ",
    paymentMethod: "পেমেন্ট মাধ্যম",
    cod: "ক্যাশ অন ডেলিভারি (COD)",
    bkash: "বিকাশ (bKash) - ক্যাশ আউট / সেন্ড মানি",
    nagad: "নগদ (Nagad) - সেন্ড মানি",
    rocket: "রকেট (Rocket) - সেন্ড মানি",
    mobileInstructions: "টাকা পাঠানোর নিয়ম:",
    instructionBkash: "আমাদের বিকাশ নম্বরে (০১৭০০-০০০০০০) টাকা সেন্ড মানি (অথবা ক্যাশআউট) করার পর নিচের বক্সে আপনার বিকাশ নম্বর এবং ট্রানজেকশন আইডি প্রদান করুন।",
    instructionNagad: "আমাদের নগদ নম্বরে (০১৭০০-০০০০০০) টাকা সেন্ড মানি করার পর নিচের বক্সে আপনার নগদ নম্বর এবং ট্রানজেকশন আইডি প্রদান করুন।",
    instructionRocket: "আমাদের রকেট নম্বরে (০১৭০০-০০০০০-০) টাকা সেন্ড মানি করার পর নিচের বক্সে আপনার রকেট নম্বর এবং ট্রানজেকশন আইডি প্রদান করুন।",
    senderNumber: "টাকা পাঠানোর মোবাইল নম্বর",
    transactionId: "ট্রানজেকশন আইডি (TrxID)",
    placeOrder: "নির্ভুল অর্ডার সাবমিট করুন",
    orderSuccess: "আপনার অর্ডারটি সফলভাবে গ্রহণ করা হয়েছে! আপনার অর্ডার আইডিটি কপি করে রাখুন।",
    orderSuccessDetails: "অ্যাডমিন শীঘ্রই আপনার টাকা প্রাপ্তি ও ডেলিভারি তথ্য ভেরিফাই করে প্রসেস করবেন।",
    
    // Role/Admin Panel
    ownerView: "ওনার ডেডিকেটেড ড্যাশবোর্ড",
    userManagement: "ইউজার রোল ম্যানেজমেন্ট",
    makeAdmin: "অ্যাডমিন হিসেবে নিযুক্ত করুন",
    revokeAdmin: "অ্যাডমিন রোল বাতিল করুন",
    userEmail: "ইউজার ইমেইল",
    userRole: "ইউজার রোল",
    ownerLabel: "মালিক (Owner)",
    adminLabel: "অ্যাডমিন (Admin)",
    customerLabel: "গ্রাহক (Customer)",
    productManagement: "প্রোডাক্ট ম্যানেজমেন্ট",
    orderManagement: "অর্ডার ট্র্যাকিং ও ম্যানেজমেন্ট",
    overviewStats: "পরিসংখ্যান ও ওভারভিউ",
    addProduct: "নতুন প্রোডাক্ট যোগ করুন",
    editProduct: "প্রোডাক্ট এডিট করুন",
    productNameBn: "প্রোডাক্ট নাম (Bangla)",
    productNameEn: "Product Name (English)",
    productPrice: "নিয়মিত মূল্য / আসল মূল্য (৳)",
    specialPriceLabel: "স্পেশাল মূল্য / অফার মূল্য (৳ - ঐচ্ছিক)",
    discountPercentLabel: "সরাসরি কত পারসেন্ট ছাড় (ঐচ্ছিক)",
    categoryLabel: "ক্যাটাগরি",
    stockCountLabel: "স্টক সংখ্যা",
    customSalesLabel: "ইতিমধ্যে কত পিস বিক্রি হয়েছে (কাস্টম সংখ্যা)",
    variantsConfigLabel: "ভেরিয়েন্ট তৈরি (কমা দিয়ে আলাদা করুন, যেমন: M, L, XL)",
    descriptionBnLabel: "প্রোডাক্ট বিবরণী (Bangla)",
    descriptionEnLabel: "Product Description (English)",
    uploadImages: "মাল্টিপল ছবির লিঙ্ক বসান (একটি করে প্রতি লাইনে)",
    imagePlaceholder: "নিচে প্রতি লাইনে একটি করে ছবির URL লিঙ্ক দিন:\nhttps://example.com/img1.jpg\nhttps://example.com/img2.jpg",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    
    // Orders System Status
    statusPending: "পেন্ডিং",
    statusProcessing: "প্রসেসিং",
    statusShipped: "ডেলিভারি চলমান",
    statusDelivered: "ডেলিভারি সম্পন্ন",
    statusCancelled: "বাতিলকৃত",
    changeStatus: "স্ট্যাটাস পরিবর্তন করুন",
    buyer: "ক্রেতা",
    paymentInfo: "পেমেন্ট তথ্য",
    noOrders: "আপনার কোনো অর্ডার হিস্ট্রি পাওয়া যায়নি।"
  },
  en: {
    appName: "Riptide",
    searchPlaceholder: "Search in Riptide...",
    loginRegister: "Login / Register",
    logout: "Log Out",
    bilingualToggle: "বাংলা",
    myOrders: "My Orders",
    adminDashboard: "Admin Dashboard",
    trackOrder: "Track Order",
    support: "Support",
    home: "Home",
    shop: "Shop",
    cart: "Cart",
    profile: "Profile",
    
    // Categories
    allCategories: "All Categories",
    digitalProduct: "Digital Product",
    uniqueProduct: "Unique Product",
    hotSell: "Hot Sell Product",
    unspecified: "General",
    
    // Banner / Slogans
    bannerTitle: "Premium Goods at Ultimate Prices",
    bannerSubtitle: "Discover verified digital assets, rare unique products, and official trending hot sellers today!",
    shopNow: "Shop Now",
    
    // Home sections
    latestArrivals: "Latest Arrivals",
    viewAll: "View All",
    noProducts: "No products found. Please check back later!",
    soldOut: "Sold Out",
    lowStock: "Low Stock",
    soldCountPostfix: "pieces already sold! 🔥",
    piecesLeft: "pieces left",
    originalPrice: "Original Price",
    discountPercent: "Discount",
    regularPrice: "Price",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    
    // Details Page
    description: "Product Description",
    variants: "Variants",
    selectVariant: "Select Variant",
    quantity: "Quantity",
    reviews: "Reviews",
    writeReview: "Write a Review",
    noReviews: "No reviews yet. Be the first to express your thoughts!",
    submitReview: "Submit Review",
    rating: "Rating",
    addComment: "Write feedback...",
    reviewSuccess: "Review added successfully!",
    
    // Cart Page
    shoppingCart: "Shopping Cart",
    emptyCart: "Your cart is empty. Please add some products!",
    checkout: "Proceed to Checkout",
    subtotal: "Subtotal",
    total: "Total",
    remove: "Remove",
    
    // Checkout Page
    checkoutTitle: "Checkout Order",
    shippingDetails: "Delivery Address",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Mobile Number",
    address: "Complete Address",
    city: "City / District",
    division: "Division",
    deliveryNotes: "Order Notes (Optional)",
    orderSummary: "Order Summary",
    totalItems: "Total Items",
    shippingCharge: "Shipping Charge",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery (COD)",
    bkash: "bKash - Cash-out / Send Money",
    nagad: "Nagad - Send Money",
    rocket: "Rocket - Send Money",
    mobileInstructions: "How to Pay:",
    instructionBkash: "Send Money (or Cash-out) to our official bKash account at 01700-000000, then paste your sender number and transaction ID (TrxID) below.",
    instructionNagad: "Send Money to our official Nagad account at 01700-000000, then paste your sender number and transaction id below.",
    instructionRocket: "Send Money to official Rocket account at 01700-00000-0, then paste your sender number and transaction id below.",
    senderNumber: "Sender's Mobile Number",
    transactionId: "Transaction ID (TrxID)",
    placeOrder: "Confirm & Place Order",
    orderSuccess: "Your order has been placed successfully! Please copy your Order ID.",
    orderSuccessDetails: "Our admin panel will verify your payment transaction ID shortly and transition your order to processing.",
    
    // Role/Admin Panel
    ownerView: "Owner Dedicated Control Desk",
    userManagement: "User Privilege Center",
    makeAdmin: "Appoint Admin",
    revokeAdmin: "Revoke Admin Privilege",
    userEmail: "User Email Address",
    userRole: "Privilege Level",
    ownerLabel: "Owner",
    adminLabel: "Admin",
    customerLabel: "Customer",
    productManagement: "Product Catalog",
    orderManagement: "Invoice Fulfillment",
    overviewStats: "Sales Analytics",
    addProduct: "Add New Product",
    editProduct: "Edit Product Details",
    productNameBn: "Product Title (Bangla)",
    productNameEn: "Product Title (English)",
    productPrice: "Regular Price (৳)",
    specialPriceLabel: "Special Discounted Price (৳ - Optional)",
    discountPercentLabel: "Flat Discount Percentage (Optional)",
    categoryLabel: "Category Group",
    stockCountLabel: "Inventory Count",
    customSalesLabel: "Number of Sales (Custom Display Value)",
    variantsConfigLabel: "Configure Variants (comma separated, e.g. M, L, XL)",
    descriptionBnLabel: "Product Description (Bangla)",
    descriptionEnLabel: "Product Description (English)",
    uploadImages: "Multiple Product Image URLs (One link per line)",
    imagePlaceholder: "Paste direct image links. One URL per text line:\nhttps://example.com/image1.jpg\nhttps://example.com/image2.jpg",
    saveChanges: "Save Listing Changes",
    cancel: "Cancel Operation",
    
    // Orders System Status
    statusPending: "Pending",
    statusProcessing: "Processing",
    statusShipped: "In Transit",
    statusDelivered: "Delivered",
    statusCancelled: "Cancelled",
    changeStatus: "Transition Status",
    buyer: "Buyer info",
    paymentInfo: "Payment Data",
    noOrders: "No orders found in your booking history."
  }
};

export function getTranslation(lang: 'bn' | 'en', key: keyof typeof translations['bn']): string {
  return translations[lang][key] || translations['en'][key] || String(key);
}
